version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - goconst
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - tagliatelle
    - testpackage
    - ireturn
    - containedctx
    - gochecknoglobals
    - paralleltest
    - tparallel
    - revive

  settings:
    govet:
      enable-all: true
    gocyclo:
      min-complexity: 10
    funlen:
      lines: 60
      statements: 30
    gosec:
      excludes:
        - G117
        - G704

run:
  timeout: 10m
  go: '1.25'
  tests: true
